splitwave-br/design-system-splitwave

- dist/components/Dropdown/Trigger/index.js
- dist/components/Dropdown/Trigger/styles.module.scss
- dist/components/Dropdown/Trigger/variables.scss
- src/components/Dropdown/Trigger/index.tsx
- src/components/Dropdown/Trigger/styles.module.scss
- src/components/Dropdown/Trigger/variables.scss
> fix(#4): Fix dropdown styles

- dist/components/Filter/Filter.stories.d.ts
- dist/components/Filter/Filter.stories.js
- dist/components/Filter/components/Button/index.d.ts
- dist/components/Filter/components/Button/index.js
- dist/components/Filter/components/Button/styles.module.scss
- dist/components/Filter/components/Content/index.d.ts
- dist/components/Filter/components/Content/index.js
- dist/components/Filter/components/Sort/index.d.ts
- dist/components/Filter/components/Sort/index.js
- dist/components/Filter/components/Sort/styles.module.scss
- dist/components/Filter/index.d.ts
- dist/components/Filter/index.js
- src/components/Filter/Filter.mdx
- src/components/Filter/Filter.stories.tsx
- src/components/Filter/components/Button/index.tsx
- src/components/Filter/components/Button/styles.module.scss
- src/components/Filter/components/Content/index.tsx
- src/components/Filter/components/Sort/index.tsx
- src/components/Filter/components/Sort/styles.module.scss
- src/components/Filter/index.ts
- Adiciona filtro de ordenação
- Mudança no tipo de borda quando o filtro não está ativo
> feat(#10): Add sort filter

- dist/components/Button/styles.module.scss
- dist/components/Button/variants.module.scss
- src/components/Button/styles.module.scss
- src/components/Button/variants.module.scss
Added important to background color of buttons to override tailwind styles on Seller
> fix(#): Added important to background color of buttons to override tailwind styles on Seller

- dist/components/Icon/components/Date.d.ts
- dist/components/Icon/components/Date.js
- dist/components/Icon/index.d.ts
- dist/components/Icon/index.js
- src/components/Icon/components/Date.tsx
- src/components/Icon/index.tsx
> feat(#18): Added date icon

- commitlint.config.js
- dist/components/Banner/index.d.ts
- dist/components/Banner/index.js
- dist/components/Banner/styles.module.scss
- dist/components/Banner/variables.scss
- dist/components/Banner/variants.module.scss
- dist/components/Filter/components/Checkboxes/index.js
- dist/components/Filter/components/Container/index.js
- dist/components/Filter/components/Responsive/index.js
- dist/components/Form/controls/Select/index.js
- dist/index.d.ts
- dist/index.js
- dist/styles/global.scss
- src/components/Banner/Banner.stories.tsx
- src/components/Banner/index.tsx
- src/components/Banner/styles.module.scss
- src/components/Banner/variables.scss
- src/components/Banner/variants.module.scss
- src/index.ts
- src/styles/global.scss
https://github.com/user-attachments/assets/c5ea6676-eea7-4d9c-9819-b1441df6b3fa
> feat(#31): added banner component in design-system

- dist/components/Filter/components/Checkboxes/index.d.ts
- dist/components/Filter/components/Checkboxes/index.js
- dist/components/Filter/components/Checkboxes/styles.module.scss
- dist/components/Filter/components/Responsive/index.js
- dist/components/Filter/index.d.ts
- src/components/Filter/Filter.stories.tsx
- src/components/Filter/components/Checkboxes/index.tsx
- src/components/Filter/components/Checkboxes/styles.module.scss
- src/components/Filter/components/Responsive/index.tsx
https://github.com/user-attachments/assets/c7d4f9eb-cadd-4b25-a535-389d6fc0f718
> fix(filter-scroll): Add scroll to checkbox filter

- src/components/Toast/styles.module.scss
- Antes
https://github.com/user-attachments/assets/a90a4c01-1ff5-4860-adad-860ab97bfc5e
- Depois
https://github.com/user-attachments/assets/e102d801-20ed-4034-851e-569249cedaf3
> fix(toast): Fix responsive toast view on mobile

- dist/components/Filter/components/Container/index.js
- dist/hooks/useClickOutside.d.ts
- dist/hooks/useClickOutside.js
- src/components/Filter/components/Container/index.tsx
- src/hooks/useClickOutside.ts
> fix(#165): Fix trigger not closing on trigger click

- dist/hooks/useClickOutside.js
- src/hooks/useClickOutside.ts
> fix(#165): Fix click outside logic

- dist/components/Dropdown/Container/index.js
- dist/components/Dropdown/Item/index.d.ts
- dist/components/Dropdown/hooks/useDropdown.d.ts
- dist/components/Dropdown/hooks/useDropdown.js
- dist/components/Dropdown/index.d.ts
- dist/components/Selector/Wrapper/index.js
- dist/components/Table/components/Cell/index.d.ts
- dist/hooks/useToggle.d.ts
- dist/hooks/useToggle.js
- dist/index.d.ts
- dist/index.js
- src/components/Dropdown/Container/index.tsx
- src/components/Dropdown/Item/index.tsx
- src/components/Dropdown/hooks/useDropdown.tsx
- src/hooks/useToggle.ts
- src/index.ts
> feat(#207): Refactor dropdown component

- dist/components/Dropdown/Item/styles.module.scss
- dist/components/Dropdown/Item/variables.scss
- dist/components/Dropdown/Trigger/index.d.ts
- dist/components/Dropdown/Trigger/index.js
- dist/components/Dropdown/Trigger/styles.module.scss
- dist/components/Dropdown/Trigger/variables.scss
- dist/components/Dropdown/Trigger/variants.module.scss
- dist/index.d.ts
- dist/index.js
- dist/styles/global.scss
- src/components/Dropdown/Container/index.tsx
- src/components/Dropdown/Item/styles.module.scss
- src/components/Dropdown/Item/variables.scss
- src/components/Dropdown/Trigger/index.tsx
- src/components/Dropdown/Trigger/styles.module.scss
- src/components/Dropdown/Trigger/variables.scss
- src/components/Dropdown/Trigger/variants.module.scss
- src/index.ts
- src/styles/global.scss
> fix(#207): Add missing useDropdown export and fix dropdown components colors

- dist/components/Filter/components/Container/index.js
- dist/components/Filter/components/Date/index.d.ts
- dist/components/Filter/components/Date/index.js
- dist/components/Filter/hooks/useFilter.js
- dist/components/Filter/hooks/useFilterUrlSync.js
- dist/components/Filter/index.d.ts
- dist/components/Filter/utils/urlHelpers.d.ts
- dist/components/Filter/utils/urlHelpers.js
- src/components/Filter/Filter.stories.tsx
- src/components/Filter/components/Container/index.tsx
- src/components/Filter/components/Date/index.tsx
- src/components/Filter/hooks/useFilter.tsx
- src/components/Filter/hooks/useFilterUrlSync.ts
- src/components/Filter/utils/urlHelpers.ts
> fix(#215): Fix date filter active state and add page as protected param

- dist/components/Filter/hooks/useFilter.js
- src/components/Filter/hooks/useFilter.tsx
> fix(#215): Remove coment

- dist/components/Form/controls/Input/styles.module.scss
- dist/components/Form/controls/Input/variables.scss
- src/components/Form/controls/Input/styles.module.scss
- src/components/Form/controls/Input/variables.scss
> fix(#216): fixed input color

- dist/components/Button/variants.module.scss
- src/components/Button/variants.module.scss
> fix(#228): Replace background image property

- dist/components/Button/variants.module.scss
- src/components/Button/variants.module.scss
> fix(button-danger): Added 'important' in the background to resolve styles conflict

- dist/components/Button/variants.module.scss
- dist/components/Icon/index.d.ts
- dist/components/Icon/index.js
- src/components/Button/variants.module.scss
> fix(#228): Change primary button variant gradient colors

- dist/components/Table/styles.module.scss
- dist/components/Table/variables.scss
- src/components/Table/Table.stories.tsx
- src/components/Table/styles.module.scss
- src/components/Table/variables.scss
Foi necessário fazer essa pequena alteração para finalizar a task de implementar darkmode na tela de transações
https://github.com/splitwave-br/admin-splitwave/issues/907
> Fix(table): added support dark on table hover

- dist/components/Form/controls/Checkbox/styles.module.scss
- src/components/Form/components/RHFCheckbox/Checkbox.stories.tsx
- src/components/Form/controls/Checkbox/styles.module.scss
CheckBox:
Checked com hover no light:
Hover dark:
> fix(check-box): added support dark

- dist/components/Table/components/Cell/Date/index.d.ts
- dist/components/Table/components/Cell/Date/index.js
- dist/components/Table/components/Cell/index.d.ts
- src/components/Table/Table.stories.tsx
- src/components/Table/components/Cell/Date/index.tsx
Add condition to render time
https://github.com/splitwave-br/admin-splitwave/issues/803
> fix(date-cell): Make time render conditional

- dist/components/DatePicker/index.d.ts
- dist/components/DatePicker/index.js
- dist/components/DatePicker/types/index.d.ts
- dist/components/Filter/components/Date/index.d.ts
- dist/components/Filter/components/Date/index.js
- dist/components/Filter/components/Date/types/index.d.ts
- dist/components/Filter/index.d.ts
- src/components/DatePicker/index.tsx
- src/components/DatePicker/types/index.ts
- src/components/Filter/Filter.stories.tsx
- src/components/Filter/components/Date/index.tsx
- src/components/Filter/components/Date/types/index.ts
[Link Issue](https://github.com/splitwave-br/seller-cashtime/issues/931)
> fix(#931): selection of dates after the current date

- dist/styles/global.scss
- src/styles/global.scss
> fix(#scroll): adjusted height

- dist/components/Form/controls/Input/styles.module.scss
- src/components/Form/controls/Input/styles.module.scss
- #338
| Result                       |
| ---------------------------- |
**Antes:**
**Depois:**
|  |
> fix(#338): adjust autofill color

- dist/components/Modal/components/Body/index.d.ts
- dist/components/Modal/components/Body/index.js
- dist/components/Modal/components/Body/styles.module.scss
- dist/components/Modal/components/Body/variables.scss
- dist/components/Modal/components/Footer/index.d.ts
- dist/components/Modal/components/Footer/index.js
- dist/components/Modal/components/Footer/styles.module.scss
- dist/components/Modal/components/Footer/variables.scss
- dist/components/Modal/components/Wrappper/index.d.ts
- dist/components/Modal/components/Wrappper/index.js
- dist/components/Modal/components/Wrappper/styles.module.scss
- dist/components/Modal/components/Wrappper/variables.scss
- src/components/Modal/components/Body/index.tsx
- src/components/Modal/components/Body/styles.module.scss
- src/components/Modal/components/Body/variables.scss
- src/components/Modal/components/Footer/index.tsx
- src/components/Modal/components/Footer/styles.module.scss
- src/components/Modal/components/Footer/variables.scss
- src/components/Modal/components/Wrappper/index.tsx
- src/components/Modal/components/Wrappper/styles.module.scss
- src/components/Modal/components/Wrappper/variables.scss
- https://github.com/splitwave-br/seller-splitwave/issues/1252
> feat(modal): Fix modal footer gradient and dark mode
